name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore plugin
        run: dotnet restore Jellyfin.Plugin.PunchPlay/Jellyfin.Plugin.PunchPlay.csproj

      - name: Restore tests
        run: dotnet restore Jellyfin.Plugin.PunchPlay.Tests/Jellyfin.Plugin.PunchPlay.Tests.csproj

      - name: Build plugin
        run: dotnet build Jellyfin.Plugin.PunchPlay/Jellyfin.Plugin.PunchPlay.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test Jellyfin.Plugin.PunchPlay.Tests/Jellyfin.Plugin.PunchPlay.Tests.csproj --configuration Release --no-restore
